#!/bin/bash

ln -s /lib/systemd/system/yerith-erp-9-0-system-daemon.service /etc/systemd/system/yerith-erp-9-0-system-daemon.service

systemctl daemon-reload &

systemctl enable yerith-erp-9-0-system-daemon.service &

systemctl start yerith-erp-9-0-system-daemon.service &

chmod +x /etc/init.d/yerith-erp-9-0-system-daemon.sh 

update-rc.d yerith-erp-9-0-system-daemon.sh defaults

/etc/init.d/yerith-erp-9-0-system-daemon.sh start & 
